name: Portal regression suite results.
on:
  push:
    branches:
      - main
#    schedule:
#     - cron: '0 9 * * *'
#     - cron: '0 22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i -g @testim/testim-cli && testim --token "BA1tIwCCRd2PxK41jFkGgVtBGVusbcvLc88p9c0Lcej3hgjXv5" --project "okKo42lPOUW4hhibLyAt" --grid "Testim-Grid" --reporters junit -r "${{secrets.TESTIM__JUNIT_REPORT_PATH }}" --suite "Regression" || true
#     Affordable Board
    - uses: mikepenz/xray-action@v2.3.0
      with:
        username: ${{ secrets.CLIENT_ID }}
        password: ${{ secrets.CLIENT_SECRET }}
        testFormat: "junit"
        testPaths: "${{secrets.TESTIM__JUNIT_REPORT_PATH }}"
        testExecKey: "XRAY-158"
        testPlanKey: "XRAY-62"
        continueOnImportError: false
        projectKey: "XRAY"   
    - name: Test results
      uses: ivanklee86/xunit-slack-reporter@v1.4.0
      env:
        SLACK_CHANNEL: "${{secrets.SLACK_QA_CHANNEL_ID}}"
        SLACK_TOKEN: "${{secrets.SLACK_BOT_TOKEN}}"
        XUNIT_GLOB: '**/*junit.xml'
        ONLY_NOTIFY_ON_ISSUES: "False"
  
